import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import {useRouter} from "next/router"
import useTranslation from "next-translate/useTranslation";

export default function Home() {
  const {t} = useTranslation()
  const {locales, asPath} = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <header>
        <ul>
          {
            locales.map((locale) => (
              <li>
                <Link href={asPath} locale={locale}>{locale}</Link>
              </li>
            ))
          }
        </ul>
        <Link href='/about'>Обо мне</Link>
      </header>
      <main className={styles.main}>
        <h1>{t('common:home', {name: 'Max'})}</h1>
      </main>
    </div>
  )
}
